// src/styles/createSwapRequest.styles.ts - Dark Mode Version
import { StyleSheet } from 'react-native';
import { Theme } from '../context/ThemeContext';

export const makeCreateSwapRequestStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.bgSecondary,
  },
  keyboardView: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: theme.textMuted,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: theme.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    minHeight: 60,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.card,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.text,
  },
  scrollContent: {
    padding: 16,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  pendingTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.primary,
    marginTop: 16,
    marginBottom: 8,
  },
  pendingText: {
    fontSize: 14,
    color: theme.textMuted,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
  },
  viewRequestButton: {
    borderRadius: 8,
    overflow: 'hidden',
  },
  viewRequestButtonGradient: {
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  viewRequestButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  assignmentCard: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.card,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    gap: 12,
  },
  taskIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.bgSecondary,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: theme.text,
  },
  taskTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.text,
    marginBottom: 20,
  },
  detailsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  detailItem: {
    flex: 1,
    alignItems: 'center',
    gap: 4,
  },
  detailLabel: {
    fontSize: 11,
    color: theme.textMuted,
    marginTop: 4,
  },
  detailValue: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.text,
  },
  pointsValue: {
    color: theme.primary,
  },
  assignmentDayBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    alignSelf: 'flex-start',
    gap: 6,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  assignmentDayText: {
    fontSize: 12,
    color: theme.textSecondary,
  },
  assignmentDayBold: {
    fontWeight: '700',
    color: theme.text,
  },
  frequencyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 16,
    alignSelf: 'flex-start',
    gap: 6,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  frequencyText: {
    fontSize: 11,
    color: theme.textSecondary,
    fontWeight: '500',
  },
  scopeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 16,
    alignSelf: 'flex-start',
    gap: 6,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  scopeBadgeText: {
    fontSize: 11,
    fontWeight: '500',
    color: theme.textSecondary,
  },
  warningCard: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: theme.errorBorder,
    backgroundColor: theme.errorBg,
  },
  warningContent: {
    flex: 1,
  },
  warningTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.error,
    marginBottom: 4,
  },
  warningText: {
    fontSize: 13,
    color: theme.error,
    lineHeight: 18,
  },
  infoSuccessCard: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: theme.primaryBorder,
    backgroundColor: theme.primaryLight,
  },
  successTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.primary,
    marginBottom: 4,
  },
  successText: {
    fontSize: 13,
    color: theme.primary,
    lineHeight: 18,
  },
  infoBanner: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  infoBannerContent: {
    flex: 1,
  },
  infoBannerTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.text,
    marginBottom: 4,
  },
  infoBannerText: {
    fontSize: 13,
    color: theme.textSecondary,
    lineHeight: 18,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.textSecondary,
    marginBottom: 12,
  },
  selectorButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.card,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: theme.border,
  },
  selectorButtonRequired: {
    borderColor: theme.errorBorder,
  },
  selectorContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  selectorText: {
    fontSize: 14,
    color: theme.text,
    fontWeight: '500',
  },
  selectorTextSelected: {
    color: theme.primary,
    fontWeight: '600',
  },
  memberList: { 
    marginTop: 8,
    backgroundColor: theme.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    overflow: 'hidden',
  },
  memberItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.borderLight,
  },
  memberInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.bgSecondary,
  },
  anyoneAvatar: {
    backgroundColor: theme.bgTertiary,
  },
  avatarImage: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  avatarText: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.textSecondary,
  },
  memberName: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.text,
    marginBottom: 2,
  },
  memberRole: {
    fontSize: 11,
    color: theme.textMuted,
  },
  noMembersContainer: {
    alignItems: 'center',
    paddingVertical: 32,
    gap: 12,
  },
  noMembersText: {
    fontSize: 14,
    color: theme.textPlaceholder,
    textAlign: 'center',
  },
  expiryOptions: {
    flexDirection: 'row',
    gap: 12,
  },
  expiryOption: {
    flex: 1,
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.border,
  },
  expiryOptionGradient: {
    paddingVertical: 10,
    alignItems: 'center',
  },
  expiryOptionText: {
    fontSize: 13,
    fontWeight: '500',
    color: theme.textSecondary,
  },
  expiryOptionTextActive: {
    color: '#fff',
  },
  expiryOptionActive: {
    borderWidth: 2,
    borderColor: theme.primary,
  },
  reasonInputGradient: {
    borderRadius: 12,
    padding: 2,
    borderWidth: 1,
    borderColor: theme.border,
  },
  reasonInput: {
    backgroundColor: theme.card,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    color: theme.text,
    minHeight: 100,
    textAlignVertical: 'top',
  },
  infoNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    borderRadius: 12,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  infoText: {
    flex: 1,
    fontSize: 12,
    color: theme.textMuted,
    lineHeight: 18,
  },
  footer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: theme.card,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  submitButton: {
    borderRadius: 12,
    overflow: 'hidden',
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
  },
  submitButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
  },
  disabledHint: {
    textAlign: 'center',
    fontSize: 12,
    color: theme.error,
    marginTop: 8,
  },
});