// src/styles/groupTasks.styles.ts - COMPLETE WITH DARK MODE AND SWAP STYLES

import { StyleSheet, Dimensions } from 'react-native';
import { Theme } from '../context/ThemeContext';

const { width } = Dimensions.get('window');

export const makeGroupTasksStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.bgSecondary,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 80,
  },
  loadingText: {
    marginTop: 12,
    color: theme.textMuted,
    fontSize: 14,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    minHeight: 56,
    backgroundColor: theme.card,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.card,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  titleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  title: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.text,
    textAlign: 'center',
  },
  connectionStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    marginTop: 2,
  },
  connectionDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  connectionText: {
    fontSize: 10,
    color: theme.textMuted,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    width: 80,
    justifyContent: 'flex-end',
  },
  draftsButton: {
    padding: 8,
  },
  swapButton: {
    position: 'relative',
    padding: 8,
  },
  swapBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: theme.error,
    borderRadius: 12,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 6,
    borderWidth: 2,
    borderColor: theme.card,
  },
  swapBadgeText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
  },
  settingsButton: {
    padding: 8,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
    paddingBottom: 100,
  },
  errorText: {
    color: theme.error,
    textAlign: 'center',
    marginBottom: 16,
    fontSize: 16,
    marginTop: 12,
  },
  retryButton: {
    borderRadius: 8,
    overflow: 'hidden',
  },
  retryButtonGradient: {
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  retryButtonText: {
    color: theme.text,
    fontWeight: '600',
    fontSize: 16,
  },
  listContainer: {
    padding: 16,
    paddingBottom: 70,
  },
  taskCard: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    position: 'relative',
  },
  disabledTaskCard: {
    opacity: 0.6,
  },
  taskHeader: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  taskIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  taskInfo: {
    flex: 1,
    marginRight: 40,
  },
  taskTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.text,
    flex: 1,
    marginRight: 8,
    lineHeight: 22,
  },
  completedTaskTitle: {
    color: theme.textMuted,
    textDecorationLine: 'line-through',
  },
  taskMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  pointsBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-start',
  },
  taskPoints: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.primary,
    
  },
  taskFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: theme.border,
    paddingTop: 12,
    marginTop: 12,
  },
  taskCreator: {
    fontSize: 12,
    color: theme.textMuted,
    flexDirection: 'row',
    alignItems: 'center',
  },
  taskDate: {
    fontSize: 12,
    color: theme.textMuted,
  },
  assignmentInfo: {
    backgroundColor: theme.bgSecondary,
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  myAssignment: {
    backgroundColor: theme.bgTertiary,
  },
  unassignedInfo: {
    backgroundColor: theme.bgSecondary,
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.border,
    borderStyle: 'dashed',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  unassignedText: {
    fontSize: 13,
    color: theme.textMuted,
    fontStyle: 'italic',
  },
  completedAssignment: {
    backgroundColor: theme.primaryLight,
    borderColor: theme.primaryBorder,
  },
  pendingAssignment: {
    backgroundColor: theme.primaryLight,
    borderColor: theme.primaryBorder,
  },
  assignmentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  assignmentStatus: {
    fontSize: 14,
    fontWeight: '600',
  },
  completeNowButton: {
    borderRadius: 8,
    marginBottom: 12,
    overflow: 'hidden',
  },
  completeNowContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    gap: 8,
  },
  completeNowText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    flex: 1,
    textAlign: 'center',
  },
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 60,
    paddingHorizontal: 20,
    marginTop: 40,
  },
  emptyText: {
    fontSize: 18,
    color: theme.textMuted,
    marginBottom: 8,
    marginTop: 16,
    textAlign: 'center',
  },
  emptyButton: {
    borderRadius: 8,
    overflow: 'hidden',
  },
  emptyButtonGradient: {
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  emptyButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },
  floatingButtonsContainer: {
    position: 'absolute',
    bottom: 90,
    right: 20,
    alignItems: 'flex-end',
    gap: 12,
    zIndex: 100,
  },
  floatingButton: {
    borderRadius: 30,
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  assignButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  createButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
  },
  reviewButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  bottomTab: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: theme.border,
    paddingTop: 8,
    paddingHorizontal: 16,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: 'space-around',
    alignItems: 'center',
    zIndex: 50,
    backgroundColor: theme.card,
  },
  tabButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    minWidth: 80,
    flex: 1,
    height: '100%',
  },
  tabText: {
    fontSize: 12,
    color: theme.textMuted,
    textAlign: 'center',
    fontWeight: '500',
  },
  activeTabText: {
    color: theme.primary,
    fontWeight: '600',
  },
  todaySection: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 2,
  },
  urgentSection: {
    borderColor: theme.error,
  },
  warningSection: {
    borderColor: theme.primary,
  },
  todaySectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  todaySectionTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  todaySectionTitle: {
    fontSize: 16,
    fontWeight: '700',
  },
  todaySectionViewAll: {
    fontSize: 14,
    color: theme.primary,
    fontWeight: '600',
  },
  todayTaskItem: {
    backgroundColor: theme.card,
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.errorBorder,
  },
  urgentTaskItem: {
    borderWidth: 2,
    borderColor: theme.error,
    backgroundColor: theme.errorBg,
  },
  lateTaskItem: {
    borderWidth: 2,
    borderColor: theme.primary,
    backgroundColor: theme.primaryLight,
  },
  warningTaskItem: {
    borderWidth: 1,
    borderColor: theme.primaryBorder,
    backgroundColor: theme.primaryLight,
  },
  todayTaskItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  todayTaskItemIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  urgentIcon: {
    backgroundColor: theme.error,
  },
  lateIcon: {
    backgroundColor: theme.primary,
  },
  warningIcon: {
    backgroundColor: theme.primary,
  },
  todayTaskItemInfo: {
    flex: 1,
  },
  todayTaskItemTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: theme.text,
    marginBottom: 4,
  },
  todayTaskItemTime: {
    fontSize: 12,
    color: theme.textMuted,
  },
  todayMoreButton: {
    alignItems: 'center',
    paddingVertical: 8,
  },
  todayMoreButtonText: {
    fontSize: 13,
    color: theme.primary,
    fontWeight: '600',
  },
  todayFAB: {
    position: 'absolute',
    bottom: 100,
    left: 20,
    right: 20,
    borderRadius: 16,
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 1000,
    overflow: 'hidden',
  },
  todayFABContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 12,
  },
  todayFABTextContainer: {
    flex: 1,
  },
  todayFABTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  todayFABCount: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: 13,
  },
  rotationBanner: {
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 8,
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  rotationBannerGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 12,
  },
  rotationBannerText: {
    flex: 1,
  },
  rotationBannerTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: theme.primary,
    marginBottom: 2,
  },
  rotationBannerMessage: {
    fontSize: 13,
    color: theme.textSecondary,
    lineHeight: 18,
  },
  warningTitle: {
    color: theme.primary,
  },
  warningMessage: {
    color: theme.textSecondary,
  },
  successTitle: {
    color: theme.primary,
  },
  successMessage: {
    color: theme.textSecondary,
  },
  creationDayBanner: {
    marginHorizontal: 16,
    marginVertical: 12,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  bannerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  bannerTextContainer: {
    flex: 1,
  },
  bannerTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.text,
    marginBottom: 2,
  },
  bannerSubtitle: {
    fontSize: 13,
    color: theme.textMuted,
  },
  bannerStats: {
    gap: 8,
    marginBottom: 8,
  },
  statRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statText: {
    fontSize: 14,
    color: theme.textSecondary,
    flex: 1,
  },
  successText: {
    color: theme.primary,
  },
  warningText: {
    color: theme.primary,
  },
  tasksNeededBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.primaryLight,
    padding: 10,
    borderRadius: 8,
    marginTop: 4,
    gap: 8,
    borderWidth: 1,
    borderColor: theme.primaryBorder,
  },
  tasksNeededText: {
    fontSize: 13,
    color: theme.primary,
    fontWeight: '600',
    flex: 1,
  },
  progressContainer: {
    marginTop: 8,
    marginBottom: 8,
    paddingHorizontal: 4,

  },
  progressBar: {
    height: 6,
    backgroundColor: theme.bgTertiary,
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: 4,
  },
  progressFill: {
    height: '100%',
    backgroundColor: theme.primary,
    borderRadius: 3,
  },
  progressText: {
    fontSize: 11,
    color: theme.textMuted,
    marginTop: 4,
    textAlign: 'center',
  },
  rotationWarningBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.primaryLight,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginTop: 4,
    gap: 4,
    borderWidth: 1,
    borderColor: theme.primaryBorder,
  },
  rotationWarningText: {
    fontSize: 10,
    color: theme.primary,  
    fontWeight: '600',
  },
  // ===== SWAP INDICATOR STYLES =====
  swappedTaskCard: {
    borderLeftWidth: 4,
    borderLeftColor: '#F59E0B',
  },
  swapIndicatorBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
    gap: 4,
    backgroundColor: '#F59E0B',
  },
  swapIndicatorText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '600',
  },
  swapInfoTooltip: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    borderRadius: 8,
    marginBottom: 8,
    gap: 6,
    borderWidth: 1,
  },
  swapInfoText: {
    fontSize: 11,
    fontWeight: '500',
    flex: 1,
  },
  viewSwapLink: {
    fontSize: 11,
    fontWeight: '600',
  },
  dueDateText: {
  fontSize: 11,
  marginTop: 4,
  marginLeft: 28,
},
pendingBadge: {
  position: 'absolute',
  top: -6,
  right: -6,
  backgroundColor: '#fff',
  borderRadius: 12,
  minWidth: 20,
  height: 20,
  justifyContent: 'center',
  alignItems: 'center',
  paddingHorizontal: 5,
  borderWidth: 2,
  borderColor: theme.error,
  zIndex: 10,
},
pendingBadgeText: {
  color: theme.error,
  fontSize: 10,
  fontWeight: 'bold',
},
});