// src/styles/rotationSchedule.styles.ts
import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const rotationScheduleStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fa',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
    minHeight: 60,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  titleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  title: {
    fontSize: 16,
    fontWeight: '600',
    color: '#212529',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 12,
    color: '#868e96',
    marginTop: 2,
    textAlign: 'center',
  },
  refreshButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 100,
  },
  loadingText: {
    marginTop: 12,
    color: '#868e96',
    fontSize: 14,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  errorText: {
    fontSize: 16,
    color: '#fa5252',
    textAlign: 'center',
    marginVertical: 10,
    fontWeight: '600',
  },
  errorSubText: {
    fontSize: 14,
    color: '#868e96',
    textAlign: 'center',
    marginBottom: 20,
  },
  retryButton: {
    borderRadius: 8,
    overflow: 'hidden',
  },
  retryButtonGradient: {
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  retryButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  weeksScroll: {
    marginHorizontal: 16,
    marginTop: 12,
  },
  weeksContainer: {
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 8,
  },
  weekTab: {
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#e9ecef',
    minWidth: 60,
  },
  weekTabGradient: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  weekTabSelected: {
    borderColor: '#2b8a3e',
  },
  weekTabText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#495057',
  },
  weekTabTextSelected: {
    color: 'white',
  },
  currentIndicator: {
    position: 'absolute',
    top: -2,
    right: -2,
  },
  taskIndicator: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 16,
    height: 16,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  taskIndicatorText: {
    color: 'white',
    fontSize: 8,
    fontWeight: 'bold',
  },
  toggleContainer: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginVertical: 12,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  toggleButton: {
    flex: 1,
  },
  toggleGradient: {
    paddingVertical: 10,
    alignItems: 'center',
  },
  toggleText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#495057',
  },
  toggleTextActive: {
    color: 'white',
  },
  toggleActive: {
    borderWidth: 1,
    borderColor: '#2b8a3e',
  },
  predictionsContainer: {
    paddingHorizontal: 16,
  },
  predictionsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#212529',
    marginBottom: 12,
    marginTop: 8,
  },
  predictionCard: {
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  nextWeekCard: {
    borderColor: '#2b8a3e',
    borderWidth: 2,
  },
  predictionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  weekTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  predictionWeek: {
    fontSize: 15,
    fontWeight: '700',
    color: '#212529',
  },
  currentBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
  },
  currentBadgeText: {
    color: 'white',
    fontSize: 9,
    fontWeight: '700',
  },
  fairnessBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  fairnessText: {
    fontSize: 11,
    fontWeight: '600',
  },
  fairnessExplanation: {
    marginBottom: 12,
  },
  explanationText: {
    fontSize: 11,
    color: '#868e96',
    fontStyle: 'italic',
  },
  assignmentsList: {
    gap: 10,
    marginBottom: 12,
  },
  assignmentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  memberContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    width: 100,
  },
  memberAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  memberInitial: {
    fontSize: 12,
    fontWeight: '600',
    color: '#495057',
  },
  memberName: {
    fontSize: 12,
    fontWeight: '500',
    color: '#212529',
    flex: 1,
  },
  taskContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  taskBadge: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
  },
  taskTitle: {
    fontSize: 11,
    fontWeight: '600',
    flex: 1,
  },
  pointsBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  pointsText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#e67700',
  },
  fairnessNote: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#e9ecef',
  },
  noteText: {
    fontSize: 11,
    color: '#868e96',
    flex: 1,
  },
  cycleCard: {
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  cycleTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2b8a3e',
    marginBottom: 4,
  },
  cycleDescription: {
    fontSize: 12,
    color: '#868e96',
    marginBottom: 16,
  },
  cycleGrid: {
    marginBottom: 12,
  },
  cycleHeader: {
    flexDirection: 'row',
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  cycleHeaderText: {
    flex: 1,
    fontSize: 10,
    fontWeight: '600',
    color: '#868e96',
    textAlign: 'center',
  },
  cycleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
    paddingHorizontal: 4,
  },
  cycleMemberName: {
    width: 60,
    fontSize: 11,
    fontWeight: '500',
    color: '#212529',
  },
  cycleCell: {
    flex: 1,
    alignItems: 'center',
  },
  cycleRankBadge: {
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 8,
    borderWidth: 1,
  },
  cycleRankText: {
    fontSize: 10,
    fontWeight: '600',
  },
  cycleNote: {
    fontSize: 10,
    color: '#868e96',
    fontStyle: 'italic',
  },
  explanationCard: {
    borderRadius: 16,
    padding: 16,
    marginVertical: 16,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  explanationTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#212529',
    marginBottom: 12,
  },
  explanationPoint: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  explanationPointText: {
    flex: 1,
    fontSize: 13,
    color: '#495057',
  },
  currentWeekBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginVertical: 8,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#b2f2bb',
    gap: 8,
  },
  currentWeekText: {
    flex: 1,
    fontSize: 13,
    color: '#2b8a3e',
  },
  statsCard: {
    marginHorizontal: 16,
    marginVertical: 8,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  statsTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#212529',
    marginBottom: 12,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  statItem: {
    flex: 1,
    minWidth: '45%',
    alignItems: 'center',
    paddingVertical: 10,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
  },
  statNumber: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2b8a3e',
    marginBottom: 2,
  },
  statLabel: {
    fontSize: 11,
    color: '#868e96',
  },
  distributionCard: {
    marginHorizontal: 16,
    marginVertical: 8,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  distributionTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#212529',
    marginBottom: 16,
  },
  distributionGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dayColumn: {
    alignItems: 'center',
    width: (width - 64) / 7,
  },
  dayLabel: {
    fontSize: 10,
    color: '#868e96',
    marginBottom: 8,
  },
  dayBarContainer: {
    height: 40,
    justifyContent: 'flex-end',
    marginBottom: 4,
  },
  dayBar: {
    width: 6,
    borderRadius: 3,
  },
  dayCount: {
    fontSize: 9,
    fontWeight: '600',
    color: '#495057',
  },
  tasksSection: {
    marginTop: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#212529',
  },
  taskCountBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
  },
  taskCount: {
    fontSize: 12,
    color: '#495057',
    fontWeight: '600',
  },
  taskCard: {
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#e9ecef',
    marginHorizontal: 16,
    marginBottom: 8,
  },
  taskGradient: {
    padding: 14,
  },
  currentWeekTask: {
    borderColor: '#b2f2bb',
  },
  taskHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  taskTitleContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  rankBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    borderWidth: 1,
  },
  rankText: {
    fontSize: 9,
    fontWeight: '700',
  },
  taskDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  assigneeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flex: 1,
  },
  assigneeText: {
    fontSize: 13,
    color: '#868e96',
    flex: 1,
  },
  timeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  timeText: {
    fontSize: 11,
    color: '#868e96',
  },
  categoryContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 6,
  },
  categoryText: {
    fontSize: 11,
    color: '#868e96',
  },
  emptyTasks: {
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 40,
  },
  emptyTasksText: {
    fontSize: 15,
    color: '#868e96',
    marginTop: 12,
    marginBottom: 4,
    fontWeight: '600',
  },
  emptyTasksSubtext: {
    fontSize: 13,
    color: '#adb5bd',
    textAlign: 'center',
  },
});