// src/styles/taskDetails.styles.ts - COMPLETE WITH DARK MODE ADAPTATION

import { StyleSheet } from 'react-native';
import { Theme } from '../context/ThemeContext';

export const makeTaskDetailsStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.bgSecondary,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: theme.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    minHeight: 60,
  },
  warningBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
    borderRadius: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: theme.primaryBorder,
    backgroundColor: theme.primaryLight,
  },
  warningContent: {
    flex: 1,
  },
  warningTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.primary,
    marginBottom: 2,
  },
  warningText: {
    fontSize: 12,
    color: theme.textSecondary,
    lineHeight: 16,
  },
  editButtonDisabled: {
    opacity: 0.5,
  },
  deleteButtonDisabled: {
    opacity: 0.5,
  },
  deleteButtonTextDisabled: {
    color: theme.textPlaceholder,
  },
  weekAssignmentAvatarImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.card,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  titleContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  title: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.text,
    textAlign: 'center',
  },
  editButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.card,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  headerSpacer: {
    width: 36,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 80,
  },
  loadingText: {
    marginTop: 12,
    color: theme.textMuted,
    fontSize: 14,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    color: theme.error,
    textAlign: 'center',
    marginBottom: 16,
    fontSize: 16,
    marginTop: 12,
  },
  retryButton: {
    borderRadius: 8,
    overflow: 'hidden',
  },
  retryButtonGradient: {
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  retryButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyText: {
    fontSize: 16,
    color: theme.textMuted,
    marginTop: 16,
    textAlign: 'center',
  },
  content: {
    flex: 1,
    padding: 16,
  },
  card: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.card,
  },
  taskHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  taskIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: theme.primaryBorder,
    backgroundColor: theme.primaryLight,
  },
  taskTitleContainer: {
    flex: 1,
  },
  taskTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.text,
    marginBottom: 6,
  },
  pointsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
    gap: 4,
    backgroundColor: theme.primaryLight,
  },
  pointsText: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.primary,
    marginLeft: 4,
  },
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  sectionIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.bgSecondary,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: theme.text,
  },
  description: {
    fontSize: 14,
    color: theme.textMuted,
    lineHeight: 20,
  },
  detailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 24,
  },
  detailItem: {
    width: '48%',
  },
  detailLabel: {
    fontSize: 11,
    color: theme.textMuted,
    marginBottom: 2,
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.text,
  },
  weekInfoCard: {
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.border,
    gap: 8,
    backgroundColor: theme.bgSecondary,
  },
  weekInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  weekInfoLabel: {
    fontSize: 13,
    color: theme.textMuted,
    width: 45,
  },
  weekInfoValue: {
    fontSize: 13,
    fontWeight: '500',
    color: theme.text,
    flex: 1,
  },
  daysContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  dayChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 4,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  todayDayChip: {
    borderColor: theme.primary,
    backgroundColor: theme.primaryLight,
  },
  dayText: {
    fontSize: 12,
    color: theme.textSecondary,
    fontWeight: '500',
  },
  todayDayText: {
    color: theme.primary, 
    fontWeight: '700',
  },
  todayDayLabel: {
    fontSize: 9,
    color: theme.primary,
    fontWeight: '600',
    backgroundColor: theme.card,
    paddingHorizontal: 3,
    paddingVertical: 1,
    borderRadius: 6,
    marginLeft: 2,
  },
  timeSlotsContainer: {
    gap: 8,
  },
  timeSlotCard: {
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  currentTimeSlotCard: {
    borderColor: theme.primaryBorder,
    borderWidth: 2,
    backgroundColor: theme.primaryLight,
  },
  timeSlotHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  timeSlotTime: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.text,
    flex: 1,
  },
  currentTimeSlotTime: {
    color: theme.primary,
    fontWeight: '600',
  },
  slotPointsBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    backgroundColor: theme.primaryLight,
  },
  slotPointsText: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.primary,
  },
  timeSlotLabel: {
    fontSize: 12,
    color: theme.textMuted,
    marginLeft: 26,
    marginBottom: 2,
  },
  activeSlotIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.primaryLight,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    alignSelf: 'flex-start',
    gap: 4,
    marginTop: 4,
  },
  activeSlotText: {
    fontSize: 11,
    color: theme.primary,
    fontWeight: '500',
  },
  timeSlotNote: {
    fontSize: 11,
    color: theme.textMuted,
    fontStyle: 'italic',
    marginTop: 6,
  },
  assignmentCard: {
    borderRadius: 10,
    padding: 16,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  assignmentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  assignmentInfo: {
    flex: 1,
  },
  assignmentDate: {
    fontSize: 13,
    color: theme.textSecondary,
  },
  submissionStatusCard: {
    borderRadius: 10,
    padding: 14,
    marginBottom: 12,
    borderWidth: 2,
  },
  submissionStatusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  statusIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusTextContainer: {
    flex: 1,
  },
  submissionStatusLabel: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 2,
    letterSpacing: 0.5,
  },
  submissionStatusDescription: {
    fontSize: 12,
    lineHeight: 18,
  },
  timerContainer: {
    marginTop: 10,
    marginLeft: 50,
  },
  timerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 16,
    alignSelf: 'flex-start',
    gap: 4,
  },
  timerText: {
    fontSize: 12,
    fontWeight: '600',
  },
  urgentTimerBadge: {},
  urgentMessage: {
    fontSize: 11,
    color: theme.error,
    fontWeight: '600',
    marginTop: 4,
    marginLeft: 4,
  },
  waitingContainer: {
    marginTop: 10,
    marginLeft: 50,
  },
 waitingBadge: {
  flexDirection: 'row',
  alignItems: 'center',
  paddingHorizontal: 10,
  paddingVertical: 4,
  borderRadius: 16,
  alignSelf: 'flex-start',
  gap: 4,
  backgroundColor: theme.bgSecondary,
},
  waitingText: {
    fontSize: 12,
    color: theme.primary,
    fontWeight: '600',
  },
  notAssignedCard: {
    borderRadius: 10,
    padding: 20,
    borderWidth: 1,
    borderColor: theme.border,
    alignItems: 'center',
    gap: 10,
    backgroundColor: theme.bgSecondary,
  },
  notAssignedText: {
    fontSize: 14,
    color: theme.textMuted,
    textAlign: 'center',
  },
  notAssignedSubtext: {
    fontSize: 12,
    color: theme.textPlaceholder,
    textAlign: 'center',
    marginTop: 4,
  },
  submissionHistoryCard: {
    backgroundColor: theme.card,
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.border,
    position: 'relative',
  },
  todaySubmissionCard: {
    borderColor: theme.primary,
    borderWidth: 2,
  },
  todayBadge: {
    position: 'absolute',
    top: -8,
    right: 8,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
    gap: 4,
    zIndex: 1,
    backgroundColor: theme.error,
  },
  todayBadgeText: {
    color: '#fff',
    fontSize: 9,
    fontWeight: '600',
  },
  submissionHistoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 6,
  },
  statusIconSmall: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  submissionHistoryInfo: {
    flex: 1,
  },
  submissionHistoryStatus: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 2,
  },
  submissionHistoryDate: {
    fontSize: 11,
    color: theme.textMuted,
  },
  todayText: {
    color: theme.error,
    fontWeight: '600',
  },
  submittedDate: {
    fontSize: 11,
    color: theme.textMuted,
    marginBottom: 6,
    marginLeft: 38,
  },
  submissionHistoryMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginLeft: 38,
    marginTop: 2,
    flexWrap: 'wrap',
  },
  hasPhotoBadgeSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    gap: 4,
    backgroundColor: theme.primaryLight,
  },
  hasPhotoTextSmall: {
    fontSize: 10,
    color: theme.primary,
  },
  hasNotesBadgeSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    gap: 4,
    backgroundColor: theme.primaryLight,
  },
  hasNotesTextSmall: {
    fontSize: 10,
    color: theme.primary,
  },
  pointsEarned: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.primary,
    marginLeft: 'auto',
  },
  adminFeedbackPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    borderRadius: 6,
    marginTop: 6,
    marginLeft: 38,
    gap: 4,
    backgroundColor: theme.errorBg,
  },
  adminFeedbackPreviewText: {
    fontSize: 10,
    color: theme.error,
    flex: 1,
    fontStyle: 'italic',
  },
  upcomingCard: {
    backgroundColor: theme.card,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.border,
    position: 'relative',
  },
  todayUpcomingCard: {
    borderColor: theme.primary,
    borderWidth: 2,
  },
  upcomingTodayBadge: {
    position: 'absolute',
    top: -6,
    right: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    zIndex: 1,
    backgroundColor: theme.primary,
  },
  upcomingTodayBadgeText: {
    color: '#fff',
    fontSize: 8,
    fontWeight: '600',
  },
  upcomingCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  upcomingUserInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
  },
  upcomingAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  upcomingAvatarText: {
    color: theme.textSecondary,
    fontSize: 12,
    fontWeight: 'bold',
  },
  upcomingUserDetails: {
    flex: 1,
  },
  upcomingUserName: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.text,
    marginBottom: 1,
  },
  upcomingTaskName: {
    fontSize: 11,
    color: theme.textMuted,
  },
  upcomingStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    gap: 4,
  },
  upcomingStatusText: {
    fontSize: 9,
    fontWeight: '600',
  },
  upcomingDetails: {
    gap: 4,
    marginLeft: 34,
  },
  upcomingDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  upcomingDetailText: {
    fontSize: 11,
    color: theme.textMuted,
  },
  adminInfoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 10,
    marginBottom: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: theme.primaryBorder,
    backgroundColor: theme.primaryLight,
  },
  adminInfoContent: {
    flex: 1,
  },
  adminInfoTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.primary,
    marginBottom: 2,
  },
  adminInfoText: {
    fontSize: 12,
    color: theme.primary,
    lineHeight: 16,
  },
  assigneeInfo: {
    padding: 12,
    borderRadius: 10,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  assigneeLabel: {
    fontSize: 11,
    color: theme.textMuted,
    marginBottom: 2,
  },
  assigneeValue: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.text,
  },
  rotationInfo: {
    padding: 12,
    borderRadius: 10,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  rotationLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.textSecondary,
    marginBottom: 8,
  },
  rotationMembersList: {
    gap: 6,
  },
  rotationMemberItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  rotationMemberAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  currentAssigneeAvatar: {
    borderColor: theme.primary,
    backgroundColor: theme.primaryLight,
  },
  rotationMemberInitial: {
    fontSize: 12,
    fontWeight: 'bold',
    color: theme.textSecondary,
  },
  rotationMemberName: {
    fontSize: 13,
    color: theme.textSecondary,
  },
  currentAssigneeName: {
    fontWeight: '600',
    color: theme.primary,
  },
  assignmentsContainer: {
    gap: 8,
  },
  assignmentsSubtitle: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.textSecondary,
    marginBottom: 4,
  },
  adminAssignmentCard: {
    backgroundColor: theme.card,
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: theme.border,
    marginBottom: 6,
    position: 'relative',
  },
  todayAdminCard: {
    borderColor: theme.primary,
    borderWidth: 2,
  },
  todayAdminBadge: {
    position: 'absolute',
    top: -6,
    right: 6,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    gap: 3,
    zIndex: 1,
    backgroundColor: theme.error,
  },
  todayAdminBadgeText: {
    color: '#fff',
    fontSize: 8,
    fontWeight: '600',
  },
  adminAssignmentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  userAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  avatarImage: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  userAvatarText: {
    color: theme.textSecondary,
    fontSize: 12,
    fontWeight: 'bold',
  },
  userDetails: {
    flex: 1,
  },
  userName: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.text,
  },
  assignmentDateSmall: {
    fontSize: 11,
    color: theme.textMuted,
  },
  todaySmallText: {
    color: theme.error,
    fontWeight: '600',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    gap: 4,
    maxWidth: 80,
    flexShrink: 1,
  },
  statusText: {
    fontSize: 9,
    fontWeight: '600',
    flexShrink: 1,
  },
  adminAssignmentDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
    flexWrap: 'wrap',
  },
  completedText: {
    fontSize: 11,
    color: theme.textMuted,
  },
  hasPhotoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 8,
    gap: 2,
    backgroundColor: theme.primaryLight,
  },
  hasPhotoText: {
    fontSize: 8,
    color: theme.primary,
  },
  hasNotesBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 8,
    gap: 2,
    backgroundColor: theme.primaryLight,
  },
  hasNotesText: {
    fontSize: 8,
    color: theme.primary,
  },
  adminNotesPreview: {
    padding: 6,
    borderRadius: 6,
    marginTop: 6,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  adminNotesPreviewText: {
    fontSize: 10,
    color: theme.textMuted,
    fontStyle: 'italic',
  },
  moreAssignments: {
    fontSize: 12,
    color: theme.textMuted,
    textAlign: 'center',
    marginTop: 4,
    fontStyle: 'italic',
  },
  noAssignments: {
    fontSize: 12,
    color: theme.textMuted,
    fontStyle: 'italic',
  },
  memberInfoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 10,
    marginTop: 16,
    gap: 8,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  memberInfoText: {
    fontSize: 12,
    color: theme.textMuted,
    flex: 1,
  },
  deleteButton: {
    borderRadius: 10,
    overflow: 'hidden',
    marginTop: 16,
  },
  deleteButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    padding: 12,
    borderWidth: 1,
    borderColor: theme.errorBorder,
    backgroundColor: theme.errorBg,
  },
  deleteButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.error,
  },
  todayAssignmentBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
    gap: 4,
  },
  todayAssignmentBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '600',
  },
  todayAssignmentTitle: {
    color: theme.text,
    fontSize: 15,
    fontWeight: '600',
  },
  completedInfoCard: {
    flexDirection: 'row',
    padding: 12,
    borderRadius: 8,
    marginTop: 10,
    gap: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.primaryBorder,
    backgroundColor: theme.primaryLight,
  },
  completedInfoText: {
    flex: 1,
  },
  completedTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.primary,
    marginBottom: 1,
  },
  completedDate: {
    fontSize: 11,
    color: theme.primary,
  },
  viewDetailsIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: theme.border,
    gap: 4,
  },
  viewDetailsText: {
    fontSize: 11,
    color: theme.textSecondary,
  },
  todayAssignmentCard: {
    borderWidth: 2,
    borderColor: theme.error,
  },
  overdueBadge: {
    backgroundColor: theme.error,
  },
  completedBadge: {
    backgroundColor: theme.primary,
  },
  overdueCard: {
    borderWidth: 2,
    borderColor: theme.error,
  },
  completedCard: {
    borderWidth: 2,
    borderColor: theme.primary,
  },
  overdueInfoCard: {
    flexDirection: 'row',
    padding: 12,
    borderRadius: 8,
    marginTop: 10,
    gap: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.errorBorder,
    backgroundColor: theme.errorBg,
  },
  overdueInfoText: {
    flex: 1,
  },
  overdueTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.error,
    marginBottom: 1,
  },
  overdueDate: {
    fontSize: 11,
    color: theme.error,
  },
  neglectedText: {
    fontSize: 10,
    color: theme.error,
    fontStyle: 'italic',
    marginTop: 2,
  },
  lateText: {
    fontSize: 10,
    color: theme.primary,
    fontStyle: 'italic',
    marginTop: 2,
  },
  progressContainer: {
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  progressBar: {
    height: 6,
    backgroundColor: theme.bgTertiary,
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: 4,
  },
  progressFill: {
    height: '100%',
    backgroundColor: theme.primary,
    borderRadius: 3,
  },
  progressText: {
    fontSize: 11,
    color: theme.textMuted,
    textAlign: 'center',
  },
  timeSlotItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  completedTimeSlotItem: {
    backgroundColor: theme.bgSecondary,
  },
  submittableTimeSlotItem: {
    backgroundColor: theme.primaryLight,
  },
  timeSlotIconContainer: {
    width: 32,
    marginRight: 12,
  },
  timeSlotInfo: {
    flex: 1,
  },
  timeSlotTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.text,
    marginBottom: 2,
  },
  timeSlotPoints: {
    fontSize: 12,
    color: theme.textMuted,
  },
  completedBadgeText: {
    fontSize: 11,
    color: theme.primary,
    fontWeight: '500',
  },
  availableBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: theme.primaryLight,
  },
  availableBadgeText: {
    fontSize: 11,
    color: theme.primary,
    fontWeight: '500',
  },
  pendingBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: theme.bgTertiary,
  },
  pendingBadgeText: {
    fontSize: 11,
    color: theme.textMuted,
    fontWeight: '500',
  },
  // ===== PENDING ASSIGNMENTS STYLES =====
  pendingAssignmentCard: {
    backgroundColor: theme.card,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: theme.border,
    position: 'relative',
  },
  todayPendingCard: {
    borderColor: theme.primary,
    borderWidth: 2,
    backgroundColor: theme.primaryLight,
  },
  overduePendingCard: {
    borderColor: theme.error,
    borderWidth: 2,
    backgroundColor: theme.errorBg,
  },
  pendingCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  pendingIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pendingInfo: {
    flex: 1,
  },
  pendingTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.text,
    marginBottom: 2,
  },
  pendingDate: {
    fontSize: 12,
    color: theme.textMuted,
  },
  todayPendingText: {
    color: theme.primary,
    fontWeight: '600',
  },
  overduePendingText: {
    color: theme.error,
    fontWeight: '600',
  },
  pendingPointsBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
    marginTop: 8,
    marginLeft: 52,
    gap: 4,
  },
  pendingPointsText: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.primary,
  },
  // ===== GROUPED BY DAY STYLES =====
  dayGroupContainer: {
    marginBottom: 16,
  },
  dayGroupHeader: {
    marginBottom: 8,
  },
  dayGroupBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    alignSelf: 'flex-start',
    backgroundColor: theme.bgSecondary,
  },
  todayDayGroupBadge: {
    borderWidth: 1,
    borderColor: theme.primaryBorder,
    backgroundColor: theme.primaryLight,
  },
  dayGroupTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.text,
    marginRight: 8,
  },
  dayGroupDate: {
    fontSize: 11,
    color: theme.textMuted,
  },
  weekAssignmentTime: {
    fontSize: 12,
    color: theme.textSecondary,
  },
  weekAssignmentCard: {
    backgroundColor: theme.card,
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: theme.border,
  },
  currentUserAssignmentCard: {
    borderColor: theme.primary,
    borderWidth: 2,
    backgroundColor: theme.primaryLight,
  },
  dueTodayAssignmentCard: {
    borderColor: theme.error,
    borderWidth: 2,
    backgroundColor: theme.errorBg,
  },
  dueTodayLabel: {
    fontWeight: '600',
    color: theme.error,
  },
  weekAssignmentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  weekAssignmentUser: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  weekAssignmentAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.bgSecondary,
  },
  currentUserAvatar: {
    borderColor: theme.primary,
    borderWidth: 2,
    backgroundColor: theme.primaryLight,
  },
  weekAssignmentAvatarText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.textSecondary,
  },
  weekAssignmentUserName: {
    fontSize: 14,
    fontWeight: '500',
    color: theme.text,
    marginBottom: 2,
  },
  currentUserLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.primary,
  },
  weekAssignmentStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  weekAssignmentStatusText: {
    fontSize: 11,
    fontWeight: '600',
  },
  weekAssignmentFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  weekAssignmentPoints: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    gap: 4,
    backgroundColor: theme.primaryLight,
  },
  weekAssignmentPointsText: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.primary,
  },
  weekAssignmentCompleted: {
    fontSize: 11,
    color: theme.textMuted,
  },
});